name: fairlife_member_app
description: Android Flutter app for Fairlife members to request adhoc funds.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^8.1.7
  google_fonts: ^6.2.1
  http: ^1.2.2
  image_picker: ^1.1.2
  intl: ^0.19.0
  path: ^1.9.0
  pdf: ^3.11.1
  shared_preferences: ^2.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.4

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/logo2.png
    - assets/splash_logo.png
    - assets/splash_branding.png

flutter_launcher_icons:
  android: true
  ios: false
  image_path: assets/logo.png
  adaptive_icon_background: '#012970'
  adaptive_icon_foreground: assets/logo.png
  min_sdk_android: 21

flutter_native_splash:
  color: '#012970'
  image: assets/splash_logo.png
  color_dark: '#012970'
  image_dark: assets/splash_logo.png
  android: true
  ios: false
  web: false
  android_12:
    color: '#012970'
    image: assets/splash_logo.png
    color_dark: '#012970'
    image_dark: assets/splash_logo.png
