name: fairlife_member_app
description: Android Flutter app for Fairlife members to request adhoc funds.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^8.1.7
  google_fonts: ^6.2.1
  http: ^1.2.2
  image_picker: ^1.1.2
  intl: ^0.19.0
  path: ^1.9.0
  pdf: ^3.11.1
  shared_preferences: ^2.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true